version: "3"
services:
  ppbglobal:
    build: .
    # volumes:
    #   - .:/django
    ports:
      - 8000:8000
    image: ppbglobal:django
    container_name: ppbglobal_container
    # command: python manage.py runserver 0.0.0.0:8000
    command: bash