# Generated by Django 5.1 on 2024-09-05 01:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uname', models.CharField(editable=False, max_length=100)),
                ('pword_hash', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True)),
                ('favorite_stage', models.CharField(blank=True, max_length=1)),
                ('acct_created', models.DateTimeField()),
                ('country', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'player',
            },
        ),
    ]
