# Generated by Django 5.1 on 2024-09-05 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='acct_created',
            field=models.DateTimeField(default=1725500781.2832725),
        ),
    ]
