# Generated by Django 5.1 on 2024-09-08 22:55

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userprofile_acct_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='acct_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 8, 18, 55, 32, 423437)),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='players',
        ),
        migrations.CreateModel(
            name='Scores',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.FloatField()),
                ('date', models.DateTimeField(default=datetime.datetime(2024, 9, 8, 18, 55, 32, 423437))),
                ('is_global', models.BooleanField(default=False)),
                ('user_uuid', models.ForeignKey(db_column='user_uuid', on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'db_table': 'scores',
            },
        ),
    ]
